#!/usr/bin/env python3
"""satellites.py — the satellite compiler: cited repos → knowledge + tooling.

Every `repo:`-marked entry in data/tools.yml becomes a SATELLITE: a pointer +
SHA-pinned digest + generated skill — never vendored code. Three subcommands,
split so the CI finish line stays offline-deterministic:

  sync    (network, gh CLI)  refresh data/satellites.yml from the GitHub API:
          stars, pushed_at, latest release, HEAD sha, fetched_at. Run locally
          or by the weekly freshness workflow — never inside `make check`.
  build   (offline)          compile skills/use-<slug>/SKILL.md from
          data/satellites.yml + the hand-curated KNOWLEDGE.md digest.
          Deterministic: same data => byte-identical skills.
  build --check              drift gate: committed generated skills must match.

Staleness is MEASURED, not promised: each satellite records the sha its digest
was written against (digest_sha); sync flags STALE when upstream HEAD moved.
A STALE satellite stays useful and says so — honest ❌ over silent rot.

Design rationale: docs/SATELLITES.md.
"""

from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "data"
SAT = DATA / "satellites.yml"
SKILLS = ROOT / "skills"


def slug(repo: str) -> str:
    return repo.split("/")[1].lower().replace(".", "-").replace("_", "-")


def gh(path: str) -> dict:
    out = subprocess.run(["gh", "api", path], capture_output=True, text=True)
    return json.loads(out.stdout) if out.returncode == 0 else {}


def sync() -> None:
    """Refresh live facts per satellite (network; keeps digest fields intact)."""
    tools = yaml.safe_load((DATA / "tools.yml").read_text())
    existing = {s["repo"]: s for s in (yaml.safe_load(SAT.read_text()) or [])} if SAT.exists() else {}
    fetched_at = subprocess.run(["date", "-u", "+%Y-%m-%d"], capture_output=True,
                                text=True).stdout.strip()
    sats = []
    for e in tools:
        repo = e.get("repo")
        if not repo:
            continue
        meta = gh(f"repos/{repo}")
        head = gh(f"repos/{repo}/commits?per_page=1")
        release = gh(f"repos/{repo}/releases/latest")
        prev = existing.get(repo, {})
        head_sha = (head[0]["sha"][:12] if isinstance(head, list) and head else
                    prev.get("head_sha", ""))
        sat = {
            "repo": repo,
            "slug": slug(repo),
            "name": e["name"],
            "url": e["url"],
            "blurb": e["blurb"],
            "category": e.get("category", ""),
            "license": meta.get("license", {}).get("spdx_id") or prev.get("license", "UNVERIFIED"),
            "stars": meta.get("stargazers_count", prev.get("stars", 0)),
            "pushed_at": (meta.get("pushed_at") or prev.get("pushed_at", ""))[:10],
            "latest_release": release.get("tag_name") or prev.get("latest_release", "none"),
            "head_sha": head_sha,
            "fetched_at": fetched_at,
            "digest_sha": prev.get("digest_sha", ""),
        }
        sat["status"] = ("no-digest" if not sat["digest_sha"] else
                         "fresh" if sat["digest_sha"] == sat["head_sha"] else "STALE")
        sats.append(sat)
    SAT.write_text("# GENERATED by scripts/satellites.py sync — do not hand-edit\n"
                   "# (except digest_sha, which pins the sha a KNOWLEDGE.md was written against)\n"
                   + yaml.safe_dump(sats, sort_keys=False, allow_unicode=True))
    print(f"satellites: synced {len(sats)} "
          f"({sum(1 for s in sats if s['status'] == 'STALE')} stale)")


def render_skill(s: dict) -> str:
    """One generated thin skill per satellite — route + facts + supply-chain rules."""
    knowledge = SKILLS / f"use-{s['slug']}" / "KNOWLEDGE.md"
    has_digest = knowledge.exists()
    stale_note = ("" if s["status"] != "STALE" else
                  f"\n> **STALE**: digest pinned to `{s['digest_sha']}` but upstream HEAD is "
                  f"`{s['head_sha']}` — verify against the live repo before relying on details.\n")
    return f"""---
name: use-{s['slug']}
description: >
  Drive {s['name']} for design-anything work — {s['blurb']} Use when a design
  task routes to this tool ({s['category']}). GENERATED satellite skill:
  facts fetched {s['fetched_at']}; treat as a pointer, not gospel.
kind: skill
license: MIT
runtimes: [claude-code, codex, hermes]
generated: true
---

# use-{s['slug']} — satellite of {s['repo']}

GENERATED by `scripts/satellites.py build` from `data/satellites.yml` —
edit the data or `KNOWLEDGE.md`, never this file (drift-gated).
{stale_note}
## Verified facts (as of {s['fetched_at']})

| Fact | Value |
|---|---|
| Repo | https://github.com/{s['repo']} |
| License | {s['license']} |
| Stars | {s['stars']:,} |
| Last push | {s['pushed_at']} |
| Latest release | {s['latest_release']} |
| HEAD | `{s['head_sha']}` |
| Digest status | {s['status']} |

## How to use it

{"1. Read `KNOWLEDGE.md` in this folder — the SHA-pinned deep digest (architecture, how to drive it, gotchas, verify command)." if has_digest else "1. No deep digest yet — read the upstream README before use."}
2. **Supply-chain rules (non-negotiable):** this is external code — read before
   running, prefer ephemeral use over persistent install, human-gate anything
   that executes. Popularity ({s['stars']:,} stars) is not a safety proof.
3. Route outputs back through the matching design-anything gate — a satellite
   generates; only our gates say "ready".

## Verification (eval-with-teeth)

Facts above are verifiable against the live API:
`gh api repos/{s['repo']} --jq .stargazers_count`. The digest's claims are
pinned to `{s['digest_sha'] or 'none'}`; if status is STALE, re-verify before
relying on internals. Success of any run is judged by OUR gate's exit 0.

## Honest edges

A satellite is a pointer + pinned digest, never a vendored copy: upstream can
change, relicense, or die — the weekly freshness sync measures that instead of
promising otherwise.
"""


# which design-anything route each satellite category serves (flagship routing)
CATEGORY_ROUTE = {
    "text/image-to-3D": "3D-print / mesh generation (repair before ready_gate)",
    "agent-infrastructure": "execution backbone — any route that needs a DCC",
    "interior-design": "photo/scan input → construction route",
    "garment-design": "garment route (patterns, markers, interop)",
    "game-and-simulation": "game/sim route",
}

FLAGSHIP = SKILLS / "design-anything" / "SKILL.md"
MARK_BEGIN = "<!-- BEGIN:satellite-routes -->"
MARK_END = "<!-- END:satellite-routes -->"


def render_flagship_routes(sats: list[dict]) -> str:
    """The satellite-routing block injected into the flagship skill."""
    rows = ["", "| Satellite | Serves | When to load | Status |", "|---|---|---|---|"]
    for s in sats:
        route = CATEGORY_ROUTE.get(s["category"], s["category"])
        rows.append(f"| `skills/use-{s['slug']}/SKILL.md` | {route} "
                    f"| {s['blurb']} | {s['status']} |")
    rows.append("")
    return "\n".join(rows)


def inject_flagship(sats: list[dict], check: bool) -> bool:
    """Keep the flagship's satellite table compiled from data. True if drifted."""
    text = FLAGSHIP.read_text()
    if MARK_BEGIN not in text or MARK_END not in text:
        print("satellites: flagship SKILL.md missing satellite-routes markers")
        sys.exit(1)
    head, rest = text.split(MARK_BEGIN, 1)
    _, tail = rest.split(MARK_END, 1)
    generated = head + MARK_BEGIN + "\n" + render_flagship_routes(sats) + MARK_END + tail
    if check:
        return generated != text
    FLAGSHIP.write_text(generated)
    return False


def build(check: bool = False) -> None:
    """Compile generated skills + flagship routes (offline, deterministic)."""
    if not SAT.exists():
        print("satellites: no data/satellites.yml — run `sync` first")
        sys.exit(1)
    sats = yaml.safe_load(SAT.read_text())
    drift = []
    for s in sats:
        path = SKILLS / f"use-{s['slug']}" / "SKILL.md"
        generated = render_skill(s)
        if check:
            if not path.exists() or path.read_text() != generated:
                drift.append(str(path.relative_to(ROOT)))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(generated)
    if inject_flagship(sats, check):
        drift.append(str(FLAGSHIP.relative_to(ROOT)))
    if check:
        if drift:
            print(f"satellites: DRIFT in {drift} — run `make satellites`")
            sys.exit(1)
        print(f"satellites: OK ({len(sats)} generated skills + flagship routes match)")
    else:
        print(f"satellites: built {len(sats)} skills + flagship routes")


def main() -> None:
    cmd = sys.argv[1] if len(sys.argv) > 1 else "build"
    if cmd == "sync":
        sync()
    elif cmd == "build":
        build(check="--check" in sys.argv)
    else:
        print(__doc__)
        sys.exit(2)


if __name__ == "__main__":
    main()
